trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
- task: npm@1
  inputs:
    command: custom
    customCommand: 'install'
- task: npm@1
  inputs:
    command: custom
    customCommand: 'test'
  displayName: 'Run a multi-line script'
